Objective: 
1) Verify (without data snooping) that URLExtraction works.
2) Ensure that we know what is output from each function we use
    in all forseeable scenarios

ToDo:

a: Build mock dataframe (only need URL column)
- Need to ensure we cover
    - no URL
    - normal URL
    - abnormal URL
    - one URL
    - numerous URLs
    - duplicate URLs
    
One case for each should be sufficient

b: Test that the url_extraction class works

In [1]:
import pandas as pd
import importlib
import URLExtraction
from URLExtraction import url_extraction

importlib.reload(URLExtraction)

In [2]:
test_data = {
    'body': [
        '',
        'Testing, no url.',
        'Be sure to use the http protocol.',
        'http://www.exampleURL.com',
        'manythanks.cu.cc',
        'www.manythanks.cu.cc',
        'http://www.exampleURL.com, manythanks.cu.cc, www.manythanks.cu.cc, and of course discordapp.com',
        'google.com, google.com, google.com, silly.co, sample.cc, silly.co',
        'http://www.exampleURL.com, http://www.exampleURL.com, http://www.exampleURL.com',
        'google.com, google.com/test, google.com/test='
    ]
}

test_df = pd.DataFrame(test_data)

In [3]:
get_url = url_extraction()

In [4]:
out_df = get_url.df_extractor(test_df, 'body', 'url_dict')

In [5]:
out_df

,body,url_dict
0,,{}
1,"Testing, no url.",{}
2,Be sure to use the http protocol.,{}
3,http://www.exampleURL.com,{'http://www.exampleURL.com': 1}
4,manythanks.cu.cc,{'manythanks.cu.cc': 1}
5,www.manythanks.cu.cc,{'www.manythanks.cu.cc': 1}
6,"http://www.exampleURL.com, manythanks.cu.cc, w...","{'http://www.exampleURL.com': 1, 'www.manythan..."
7,"google.com, google.com, google.com, silly.co, ...","{'google.com': 3, 'silly.co': 2, 'sample.cc': 1}"
8,"http://www.exampleURL.com, http://www.exampleU...",{'http://www.exampleURL.com': 3}
9,"google.com, google.com/test, google.com/test=","{'google.com': 1, 'google.com/test,': 1, 'goog..."

In [6]:
import URLHandling
importlib.reload(URLHandling)

In [7]:
handle_urls = URLHandling.url_handling()

In [8]:
print(list(out_df.columns))

['body', 'url_dict']

In [9]:
out_df2 = handle_urls.url_replacement(out_df, 'body', 'url_dict', 'cleaned_body', indexed=True)

In [10]:
out_df2

,body,url_dict,cleaned_body
0,,{},
1,"Testing, no url.",{},"Testing, no url."
2,Be sure to use the http protocol.,{},Be sure to use the http protocol.
3,http://www.exampleURL.com,{'http://www.exampleURL.com': 1},<url1>
4,manythanks.cu.cc,{'manythanks.cu.cc': 1},<url1>
5,www.manythanks.cu.cc,{'www.manythanks.cu.cc': 1},<url1>
6,"http://www.exampleURL.com, manythanks.cu.cc, w...","{'http://www.exampleURL.com': 1, 'www.manythan...","<url1>, <url3>, <url2>, and of course <url4>"
7,"google.com, google.com, google.com, silly.co, ...","{'google.com': 3, 'silly.co': 2, 'sample.cc': 1}","<url1>, <url1>, <url1>, <url2>, <url3>, <url2>"
8,"http://www.exampleURL.com, http://www.exampleU...",{'http://www.exampleURL.com': 3},"<url1>, <url1>, <url1>"
9,"google.com, google.com/test, google.com/test=","{'google.com': 1, 'google.com/test,': 1, 'goog...","<url1>, <url2> <url3>"